name: ManualDeployToProd

on:
  workflow_dispatch:

env:
  AWS_REGION: 'ap-northeast-2'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # defaults:
    #     run:
    #         working-directory: ./src

    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v3

      - name: install npm dependencies
        run: npm install --legacy-peer-deps

      # - name: Create .env file
      #   run: |
      #     jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]'

      - name: vue build
        run: npm run build:desktop # production 빌드

      # AWS 연결
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESSKEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESSKEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          aws s3 sync ./dist/desktop s3://$BUCKET_NAME/desktop

      # - name: CloudFront Invalidation
      #   env:
      #       CLOUD_FRONT_ID: ${{ secrets.PROD_AWS_CLOUDFRONT_ID }}
      #   run: |
      #       aws cloudfront create-invalidation \
      #         --distribution-id $CLOUD_FRONT_ID --paths '/*'
